name: "SmartPlaylist2PlaylistHarder"
guid: "5A63FE63-765F-43F7-A129-661E839F83D5"
imageUrl: ""
version: "1.5.0.0"
targetAbi: "10.8.0.0"
framework: "net6.0"
owner: "JMiles42"
overview: "Smart Playlist 2 Playlist Harder! Is a system to automatically generate playlists based on a set of rules\nBuilt off of the base of SmartPlaylist by ankenyr"
description: |
  Smart Playlist 2 Playlist Harder!.
  Is a system to automatically generate playlists based on a set of rules.
  Built off of the base of SmartPlaylist by ankenyr.
category: "Playlist"
artifacts:
  - "Jellyfin.Plugin.SmartPlaylist.dll"
changelog: |
  Moved Operators to separate files
  Added logger to SmartPlaylistFileSystem
  Renamed Expression to SmartPlExpression so it no longer conflicts with Linq
  Added CompiledRule type, to replace nested generics where possible
  Added new Random Orderer, it you want a random order that is not relevent to any of the items data
  Changed DefaultTrigger from 30 minutes to 6 hours.
  Added new IsNull operator
  Implemented MaxItems
  Added New Operand properties
   -ParentName
   -GrandparentName
   -Container
  Note:  ParentName & GrandparentName are WIP and have only been tested with a library of episodes.